### ISSUE TITLE
combine index.json data with server-meta.json data

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Blog#34]
issue #20 leads to the design change such there is only _one_ initial service call for external data during the initial load of the App; it follows that `index.json` and `server-meta.json` should be combined into `app.json`

**Comment by BryanWilhite** [comment]
`index.json` sweep:

- [ ] `index.json` should be replaced with `app.json` on the Client and Client config (e.g. `*.csproj`)
- [ ] `BlogEntriesService.loadIndex()` should be changed to `BlogEntriesService.loadAppData()`
- [ ] `AppScalars.indexLocation` should be changed to `AppScalars.appDataLocation`
- [ ] for `SeoTest.ShouldGenerateSitemap()` `@"ClientApp\src\assets\data\index.json"` should be changed to `@"json\index.json"` (and conventional `webProjectInfo` should be replaced by `projectDirectoryInfo`)
- [ ] for `BlogRepositoryTest.ShouldGenerateRepositoryIndex()` `@"ClientApp\src\assets\data\index.json"` should be changed to `@"json\index.json"` (and conventional `webProjectInfo` should be replaced by `projectDirectoryInfo)

**Comment by BryanWilhite** [comment]
the schema for `app.json`:

```json
{
    "serverMeta": {},
    "index": []
}
```

**Comment by BryanWilhite** [comment]
`server-meta.json` sweep:

- [ ] `AppScalars.serverMetaLocation` should be removed
- [ ] Jasmine spec `it('should load server meta'` should be removed
- [ ] for `ProgramTest.ShouldGenerateServerMetadata()` @"ClientApp\src\assets\data\server-meta.json" should be changed to @"json\server-meta.json" (and conventional webProjectInfo should be replaced by projectDirectoryInfo)
